# Aspectos generales de programación y algoritmos

## Complejidad de algoritmos

### ¿Qué es un algoritmo?
Un algoritmo es una serie ordenada de operaciones sistemáticas que permite hacer un cálculo y hallar la solución de un tipo de problemas.

Por ejemplo:

In [1]:
def f(n):
    out = 0
    for i in range(n):
        for j in range(n):
            out += i*j
    return out

In [2]:
f(2)

1

La complejidad de un algoritmo es la **relación entre el tamaño del input $N$** y la **cantidad de operaciones para completarlo**.
Una forma de determinar la complejidad del algoritmo es **contabilizar las operaciones básicas**:
- sumas
- restas
- multiplicaciones
- divisiones
- asignación de variables
- llamados a otras funciones

Por ejemplo, en el siguiente algoritmo:

In [3]:
def f(n):
    out = 0
    for i in range(n):
        for j in range(n):
            out += i*j
    return out

El número de operaciones son:
- sumas: $N^2$
- restas: 0
- multiplicaciones: $N^2$
- divisiones: 0
- asignación de variables: $2N^2 + N + 1$
- llamados a otras funciones: 0

Así, el **total de operaciones** para completar el algoritmo es $4N^2+N+1$.

### Notación *Big-O*
A medida que el tamaño de $N$ aumenta, las operaciones de mayor orden se hacen dominantes. Así, podemos decir que la complejidad del algoritmo anterior es del orden $O(N^2)$. Esta notación, denominada ***Big-O***, es comúnmente utiilzada para **determinar la complejidad del algoritmo cuando $N$ es de gran tamaño**.

> **Nota** Un algoritmo tiene complejidad **polinomial** cuando es del tipo $O(N^c)$, donde $c$ es una constante.

### ¿Cómo deducimos el orden de un algoritmo?

En el ejemplo anterior pudimos **contar directamente** las operaciones, porque sabíamos de antemano cuántas veces se ejecutaba cada bucle ($N$ veces cada uno).

Esto **no siempre es posible**. Hay dos situaciones en que el conteo directo falla:

- el bucle **no avanza de a uno**, sino que *divide* el tamaño del problema (`n = n/2`),
- la función **se llama a sí misma** (recursión), y el número de llamados no es evidente.

Para estos casos usamos el siguiente procedimiento.

#### Método de los 4 pasos

| Paso | Pregunta que debemos responder | Qué obtenemos |
|:---:|:---|:---|
| **1** | ¿Cuál es la **operación dominante**? | *qué* vamos a contar |
| **2** | ¿Cómo cambia el problema **de un paso al siguiente**? | análisis de avance  |
| **3** | ¿Cuántos pasos $I$ se necesitan para terminar? | $I(N)$, despejado del paso 2 |
| **4** | ¿Cuál es el término dominante cuando $N \rightarrow \infty$? | $O(\cdot)$ |

> **Nota.** Los pasos 1 y 4 son siempre iguales. **El paso 2 es el que decide la familia de complejidad.**

### Complejidad logarítmica

Apliquemos el método de los 4 pasos al siguiente algoritmo:

In [4]:
def my_divide_by_two(n):
    
    out = 0
    while n > 1:
        n /= 2
        out += 1
        
    return out

In [5]:
my_divide_by_two(10)

4

**Paso 1: tamaño del input y operación dominante.**

El input es el número $N$ (el valor de `n`). La parte dominante está dentro del bucle `while`: cada iteración ejecuta un número **fijo** de operaciones (una división, una suma y dos asignaciones), independiente de $N$. Entonces

\begin{equation}
\mathrm{Total~de~operaciones} = a \times I
\end{equation}

donde $a$ es el costo (constante) de **una** iteración e $I$ es el **número de iteraciones**. Como $a$ es constante, todo el problema se reduce a **contar iteraciones**.

**Paso 2: análisis de avance.** ¿Qué le ocurre a `n` en cada iteración? Se **divide por 2**:

| Iteración $k$ | 0 | 1 | 2 | 3 | $\cdots$ | $k$ |
|:---|:---:|:---:|:---:|:---:|:---:|:---:|
| valor de `n` | $N$ | $\dfrac{N}{2}$ | $\dfrac{N}{4}$ | $\dfrac{N}{8}$ | $\cdots$ | $\dfrac{N}{2^k}$ |

entonces, el valor de `n` en cada iteración, está dado por:

\begin{equation}
n_k = \frac{N}{2^k}
\end{equation}

**Paso 3: número de iteraciones.** El bucle se detiene cuando `n` deja de ser mayor que 1, es decir, en la iteración $I$ tal que $n_I \approx 1$:

\begin{equation}
\frac{N}{2^{I}} = 1
\quad \Longrightarrow \quad
2^{I} = N
\quad \Longrightarrow \quad
I = \log_2 N
\end{equation}

> El logaritmo aparece porque es, **por definición**, la operación inversa de multiplicar repetidamente. La pregunta *"¿cuántas veces debo dividir $N$ por 2 para llegar a 1?"* **es** la definición de $\log_2 N$.

**Paso 4: término dominante.** Si cada iteración cuesta $a$ operaciones, y fuera del bucle hay $b$ operaciones fijas:

\begin{equation}
\mathrm{Total} = a \log_2 N + b
\quad \Longrightarrow \quad
O(\log N)
\end{equation}

> **Nota** Un algoritmo tiene complejidad **logarítmica** cuando es del tipo $O(\log N)$.

> **¿Por qué se escribe $O(\log N)$ sin indicar la base?**

Porque cambiar de base solo multiplica por una **constante**:

\begin{equation}
\log_b N = \frac{\log_2 N}{\log_2 b}
\end{equation}

y las constantes no afectan el orden. Dividir por 2, por 3 o por 10 en cada paso da exactamente lo mismo: todos son $O(\log N)$.

> **Nota** Un algoritmo tiene complejidad **logarítmica** cuando es del tipo $O(\log N)$.

**Verificación numérica.** Contemos las iteraciones para distintos valores de $N$:

In [6]:
import numpy as np

def contar_iteraciones(N, b=2):
    """Cuenta cuántas veces se divide N por b hasta llegar a 1"""
    n, iteraciones = N, 0
    while n > 1:
        n = n / b
        iteraciones += 1
    return iteraciones

print(f"{'N':>10} {'iteraciones I':>14} {'log2(N)':>10}")
for N in [2, 4, 8, 16, 32, 1024, 10**6]:
    print(f'{N:>10} {contar_iteraciones(N):>14} {np.log2(N):>10.2f}')

         N  iteraciones I    log2(N)
         2              1       1.00
         4              2       2.00
         8              3       3.00
        16              4       4.00
        32              5       5.00
      1024             10      10.00
   1000000             20      19.93


#### La firma del orden logarítmico

En la tabla anterior, **cada vez que $N$ se duplica se agrega una sola iteración**:

\begin{equation}
I(2N) = \log_2 (2N) = \log_2 N + 1 = I(N) + 1
\end{equation}

Por eso un algoritmo $O(\log N)$ es extraordinariamente eficiente: pasar de $N = 10^3$ a $N = 10^6$ (mil veces más datos) **solo duplica** el trabajo.

### Serie de Fibonacci y complejidad exponencial

Una operación matemática puede ser ejecutada mediante algoritmos con diferente complejidad. Por ejemplo, consideremos la serie de Fibonacci.

<img src="./imagenes/Fibonacci.png" width="800" align= center>

Esta operación puede ejecutarse de dos maneras: (1) de forma iterativa, (2) de forma recursiva

**(1) Forma iterativa.** complejidad $O(N)$

In [7]:
def my_fib_iter(n):
    
    out = [1, 1]
    
    for i in range(2, n+1):
        out.append(out[i - 1] + out[i - 2])
        
    return out[-1]

In [8]:
my_fib_iter(6)

13

**(2) Forma recursiva.** complejidad $O\left(2^N\right)$

In [9]:
def my_fib_rec(n):
    
    if n < 2:
        out = 1
    else:
        out = my_fib_rec(n-1) + my_fib_rec(n-2)
        
    return out

In [10]:
my_fib_rec(5)

8

#### ¿Por qué la versión recursiva es exponencial?

En un algoritmo recursivo **no hay bucles que contar**: cada llamado genera nuevos llamados. El paso 2 del método (la ley de avance) se escribe ahora como una **relación de recurrencia**, respondiendo dos preguntas:

1. ¿**Cuántos llamados** genera cada ejecución de la función? $\;\rightarrow\;$ **ramificación** del árbol, $c$
2. ¿**Cuánto disminuye el tamaño** en cada llamado? $\;\rightarrow\;$ **profundidad** del árbol, $p$

Para `my_fib_rec`, cada llamado con $n \geq 2$ genera **dos** llamados, de tamaños $n-1$ y $n-2$. Si $T(n)$ es el número total de llamados:

\begin{equation}
T(n) = \underbrace{T(n-1) + T(n-2)}_{\mathrm{los~dos~llamados~hijos}} + \underbrace{1}_{\mathrm{el~llamado~actual}}
\end{equation}

con $T(0) = T(1) = 1$.

#### El árbol de recursión

Dibujar el árbol de llamados es **la herramienta central** para deducir la complejidad de un algoritmo recursivo. Para `my_fib_rec(5)`:

```
fib(5)
├── fib(4)
│   ├── fib(3)
│   │   ├── fib(2)
│   │   │   ├── fib(1)  ← hoja
│   │   │   └── fib(0)  ← hoja
│   │   └── fib(1)      ← hoja
│   └── fib(2)
│       ├── fib(1)      ← hoja
│       └── fib(0)      ← hoja
└── fib(3)
    ├── fib(2)
    │   ├── fib(1)      ← hoja
    │   └── fib(0)      ← hoja
    └── fib(1)          ← hoja
```

Del árbol observamos:

- Tiene **15 nodos**: se necesitan **15 llamados** a la función para calcular `my_fib_rec(5)`.
- Tiene **8 hojas**, y cada hoja devuelve un 1. Como el resultado es la suma de las hojas, `my_fib_rec(5)` $= 8$. **El valor calculado es igual al número de hojas**: por eso el costo del algoritmo crece tan rápido como la propia serie de Fibonacci.
- `fib(3)` se calcula **2 veces**, `fib(2)` **3 veces** y `fib(1)` **5 veces**. El algoritmo **recalcula** una y otra vez los mismos valores: ahí está el desperdicio que la versión iterativa evita.

#### Del árbol al orden: contar nodos

Un árbol en que **cada nodo genera $c$ hijos** y que tiene **profundidad $p$** contiene

\begin{equation}
1 + c + c^2 + \cdots + c^{p} \approx c^{p} \quad \mathrm{nodos}
\end{equation}

```
nivel 0 :                •                 1  = 2⁰ nodo
nivel 1 :        •               •         2  = 2¹ nodos
nivel 2 :    •       •       •       •     4  = 2² nodos
nivel 3 :  •   •   •   •   •   •   •   •   8  = 2³ nodos
   ⋮                     ⋮                 ⋮
nivel N :  • • • • • • • • • • • • • • •   2^N nodos
```

\begin{equation}
\mathrm{N^\circ~de~operaciones} \;\approx\; a \cdot c^{\,p}
\end{equation}

donde $a$ = trabajo por nodo, $c$ = **ramificación** y $p$ = **profundidad**.

Para `my_fib_rec`:

- la **ramificación** es $c = 2$ (cada llamado genera 2 llamados),
- el tamaño baja **restando** ($n \rightarrow n-1$), así que la **profundidad** es $p = N$.

\begin{equation}
T(N) \leq 2^{N}
\quad \Longrightarrow \quad
O(2^N)
\end{equation}

**Verificación numérica.** Instrumentemos la función recursiva con un contador de llamados:

In [11]:
def my_fib_rec_contado(n, contador):

    contador[0] += 1               # registramos este llamado

    if n < 2:
        out = 1
    else:
        out = my_fib_rec_contado(n-1, contador) + my_fib_rec_contado(n-2, contador)

    return out

In [12]:
T = {}
for N in range(26):
    contador = [0]
    my_fib_rec_contado(N, contador)
    T[N] = contador[0]                     # n° de llamados para calcular fib(N)

print(f"{'N':>4} {'llamados T(N)':>15} {'T(N)/T(N-1)':>13}")
for N in [5, 10, 15, 20, 25]:
    print(f'{N:>4} {T[N]:>15,} {T[N]/T[N-1]:>13.3f}')

   N   llamados T(N)   T(N)/T(N-1)
   5              15         1.667
  10             177         1.624
  15           1,973         1.619
  20          21,891         1.618
  25         242,785         1.618


### Notación *Big-O* y tiempo de computación
La complejidad en la notación *Big-O* nos entrega una referencia del tiempo computacional dedicado para un determinado algoritmo.

<img src="./imagenes/08.02.01-complexity.png" width="300" align= center>

Así, por ejemplo, si consideramos un procesador Intel i7-12700K - 5GHz *($\approx$ 5 mil millones de operaciones por segundo)*:
- ```my_fib_iter(100)``` <br>tomaría $\approx$ 0.2 nanosegundos
<br>
- ```my_fib_recur(100)``` <br>tomaría $\approx$ 8 billones de años

Podemos evaluar el tiempo de ejecución con la sentencia ```%time```

In [13]:
%time a = my_fib_iter(30)

CPU times: user 5 µs, sys: 7 µs, total: 12 µs
Wall time: 17.2 µs


In [14]:
%time a = my_fib_rec(30) # No probar N>30

CPU times: user 169 ms, sys: 0 ns, total: 169 ms
Wall time: 180 ms


> **nota** En general, se deben evitar los algoritmos de complejidad exponencial

## Error absoluto y relativo

Como veremos a lo largo del curso, los métodos numéricos se basan en *aproximaciones* para representar funciones y operaciones complejas. Estas aproximaciones pueden producir dos tipos de errores:
- Errores de truncamiento: debido al uso expresiones aproximadas del procedimiento matemático exacto
- Errores de redondeo: debido a las limitaciones de representación numérica propias del computador

Para cuantificar el error utilizamos dos tipos de métricas

**Error absoluto** Corresponde al error neto de la propuesta numérica:

\begin{equation}
E_\mathrm{abs} = |\mathrm{valor~aproximado} - \mathrm{valor~exacto}|
\end{equation}

**Error relativo** Corresponde al error de la propuesta numérica respecto al valor exacto:

\begin{equation}
E_\mathrm{rel} = \frac{|\mathrm{valor~aproximado} - \mathrm{valor~exacto}|}{|\mathrm{valor~exacto}|}
\end{equation}

>**Nota** A veces, el error relativo se representa como porcentaje

Comúnmente, los métodos numéricos se basan en procesos iterativos donde una solución $x^k$ es mejorada en la iteración siguiente $x^{k+1}$. En el caso que la solución exacta no se conozca (caso más común), calculamos los errores como

- **Error absoluto** 

    \begin{equation}
    E_\mathrm{abs} = |x^{k+1} - x^{k}|
    \end{equation}

- **Error relativo** 

    \begin{equation}
    E_\mathrm{rel} = \frac{|x^{k+1} - x^{k}|}{|x^{k+1}|}
    \end{equation}

## Documentación de funciones en python

En python existen múltiples liberías, cada una con un propósito en específico. En este curso, trabajaremos con:
- `numpy`: Esencial para operaciones matemáticas con arreglos de elementos
- `pandas`: Útil para manejo de base de datos
- `matplotlib`: Herramientas para visualización de datos. En este curso utilizaremos particularmente el módulo `matplotlib.pyplot`.
- `scipy`: Funciones avanzadas para ciencia e ingeniería

A lo largo del curso iremos revisando las principales funciones de cada librería. En esta sección explicaremos como entender como acceder a la documentación oficial de cada función, y como interpretarla.

Para revisar la documentación de una función tenemos varias alternativas. Las más recomendadas son:
- Documentación oficial en línea
- Función `help`
- Caracter `?` al final de la función
- Comando `shift + tab`

>**Nota.** Por defecto, la documentación en línea está en base a la **última versión de la librería**. Es posible, sin embargo, encontrar la documentación para versiones anteriores.

Para verificar la versión de la librería que se está utilizando se debe usar el comando `library.__version__`, donde `library` corresponde a la librería en cuestión.

In [15]:
import numpy as np
print('versión de numpy: ' + np.__version__)

versión de numpy: 1.26.4


In [16]:
import matplotlib as mpl
print('versión de matplotlib: ' + mpl.__version__)

versión de matplotlib: 3.9.2


In [17]:
import scipy as sp
print('versión de scipy: ' + sp.__version__)

versión de scipy: 1.16.3


### Documentación en línea

Como ejercicio, consideremos la documentación de la función `linspace` de la libería `numpy`. Esta función será utilizada frecuentemente en el curso, y permite generar un arreglo de números distribuidos entre dos límites establecidos.

In [18]:
# generar un arreglo de 5 números entre 0 y 1
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Acá podemos ver un extracto de la documentación en línea (para la información completa ver [acá](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html))

<img src="./imagenes/linspace_online-doc.png" width="800" align= center>

Lo primero que vemos es el encabezado que muestra **todos los parámetros que necesita la función** (En este caso: `start`, `stop`, `num`, `endpoint`, `retstep`, `dtype` y `axis`). *La función esperará que todos los valores estén asignados, de lo contrario, arrojará un error.*

Luego, vemos parámetros con símbolo `=` (`num = 50`, por ejemplo). Esto indica que el parámetro **tiene un valor asignado por defecto**.

**Los parámetros con valor por defecto pueden ser omitidos al llamar a una función**. En ese caso python asumirá el valor asignado por defecto:

In [24]:
np.linspace(0,1)  # omitimos el parámetro "num"

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

El resultado es un arreglo de números igualmente espaciados entre 0 y 1, con `num = 50`.

Más abajo en la documentación, encontramos la descripción de cada parámetro. Notar que los valores con `=` están identificados como **opcional**.

<img src="./imagenes/linspace_online-doc_parameter.png" width="800" align= center>

Algunos parámetros no están disponibles en todas las versiones de la librería. Es el caso de `axis` de la función`linspace`, el cual está disponible desde la versión 1.16.0. en adelante.

<img src="./imagenes/linspace_online-doc_new-parameter.png" width="800" align= center>

Por último, tenemos el *output* de la función en el encabezado "**Return**"

<img src="./imagenes/linspace_online-doc_return.png" width="800" align= center>

Acá, por ejemplo, la documentación indica que la función entregará dos *outputs*, donde el primero corresponde al arreglo y el segundo, al espaciamiento entre valores. El segundo *output* es opcional, condicionado a la variable `retstep = True` (`False` por defecto).

In [34]:
vector, step = np.linspace(0,1,retstep=True)
print('Arreglo generado: ', vector)
print('Espaciamiento: ', step)

Arreglo generado:  [0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
Espaciamiento:  0.02040816326530612


En python también podemos llamar a la función indicando el nombre de los parámetros de entrada

In [21]:
np.linspace(start=0, stop=1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Esta última forma es más conveniente para usuarios que no conocen la función, ya que permite identificar los parámetros de entrada

De igual forma, podemos cambiar el orden de los argumentos usando este esquema:

In [22]:
np.linspace(num=5, stop=1, start=0)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

###  Comandos directos para acceder a la documentación

La opción más directa es presionando `Shift + Tab` posicionando el cursor al final de la función. Este comando depende del *IDE* utilizado, pero funciona con *Jupyter Notebook*, *Visual Studio Code* y *Google colab*.

<img src="./imagenes/shift+tab.png" width="800" align= center>

Otra alternativa es con el comando `?` o con la función `help`
```python
np.linspace?
help(np.linspace)
```

## Referencias
Kong Q., Siauw T., Bayen A. M. “[Python Programming and Numerical Methods – A Guide for Engineers and Scientists](https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html)”, 1st Ed., Academic Press, 2021
- Chapter 8. Complexity
- Chapter 9. Representation of numbers
- Calítulo 10. Errors, Good Programming Practices, and Debugging