# Aspectos generales de programación y algoritmos

## Complejidad de algoritmos

### ¿Qué es un algoritmo?
Un algoritmo es una serie ordenada de operaciones sistemáticas que permite hacer un cálculo y hallar la solución de un tipo de problemas.

Por ejemplo:

In [1]:
def f(n):
    out = 0
    for i in range(n):
        for j in range(n):
            out += i*j
    return out

La complejidad de un algoritmo es la **relación entre el tamaño del input $N$** y la **cantidad de operaciones para completarlo**.
Una forma de determinar la complejidad del algoritmo es **contabilizar las operaciones básicas**:
- sumas
- restas
- multiplicaciones
- divisiones
- asignación de variables
- llamados a otras funciones

Por ejemplo, en el siguiente algoritmo:

In [2]:
def f(n):
    out = 0
    for i in range(n):
        for j in range(n):
            out += i*j
    return out

El número de operaciones son:
- sumas: $N^2$
- restas: 0
- multiplicaciones: $N^2$
- divisiones: 0
- asignación de variables: $2N^2 + N + 1$
- llamados a otras funciones: 0

Así, el **total de operaciones** para completar el algoritmo es $4N^2+N+1$.

### Notación *Big-O*
A medida que el tamaño de $N$ aumenta, las operaciones de mayor orden se hacen dominantes. Así, podemos decir que la complejidad del algoritmo anterior es del orden $O(N^2)$. Esta notación, denominada ***Big-O***, es comúnmente utiilzada para **determinar la complejidad del algoritmo cuando $N$ es de gran tamaño**.

> **Nota** Un algoritmo tiene complejidad **polinomial** cuando es del tipo $O(N^c)$, donde $c$ es una constante.

Analicemos la complejidad del siguiente algortimo:

In [3]:
def my_divide_by_two(n):
    
    out = 0
    while n > 1:
        n /= 2
        out += 1
        
    return out

A medida que $N$ crece podemos ver que la parte dominante de este algoritmo esta dentro de la operación ```while```.

Si analizamos el número de iteraciones $I$ para un determinado $N$, notaremos que estos están en la relación $N/2^I = 1$, es decir $I\approx \log N$. Así, la complejidad de este algoritmo es $O(\log N)$.

> **Nota** Un algoritmo tiene complejidad **logarítmica** cuando es del tipo $O(\log N)$.

### Serie de Fibonacci y complejidad exponencial

Una operación matemática puede ser ejecutada mediante algoritmos con diferente complejidad. Por ejemplo, consideremos la serie de Fibonacci.

<img src="./imagenes/Fibonacci.png" width="800" align= center>

Esta operación puede ejecutarse de dos maneras: (1) de forma iterativa, (2) de forma recursiva

**(1) Forma iterativa.** complejidad $O(N)$

In [4]:
def my_fib_iter(n):
    
    out = [1, 1]
    
    for i in range(2, n+1):
        out.append(out[i - 1] + out[i - 2])
        
    return out[-1]

In [5]:
my_fib_iter(6)

13

**(2) Forma recursiva.** complejidad $O\left(2^N\right)$

In [6]:
def my_fib_rec(n):
    
    if n < 2:
        out = 1
    else:
        out = my_fib_rec(n-1) + my_fib_rec(n-2)
        
    return out

In [7]:
my_fib_rec(5)

8

> **Nota** Un algoritmo tiene complejidad **exponencial** cuando es del tipo $O(c^N)$, donde $c$ es una constante.

### Notación *Big-O* y tiempo de computación
La complejidad en la notación *Big-O* nos entrega una referencia del tiempo computacional dedicado para un determinado algoritmo.

<img src="./imagenes/08.02.01-complexity.png" width="300" align= center>

Así, por ejemplo, si consideramos un procesador Intel i7-12700K - 5GHz *($\approx$ 5 mil millones de operaciones por segundo)*:
- ```my_fib_iter(100)``` <br>tomaría $\approx$ 0.2 nanosegundos
<br>
- ```my_fib_recur(100)``` <br>tomaría $\approx$ 8 billones de años

Podemos evaluar el tiempo de ejecución con la sentencia ```%time```

In [8]:
%time a = my_fib_iter(30)

CPU times: user 13 µs, sys: 0 ns, total: 13 µs
Wall time: 19.1 µs


In [9]:
%time a = my_fib_rec(30) # No probar N>30

CPU times: user 269 ms, sys: 3.78 ms, total: 273 ms
Wall time: 292 ms


> **nota** En general, se deben evitar los algoritmos de complejidad exponencial

## Error absoluto y relativo

Como veremos a lo largo del curso, los métodos numéricos se basan en *aproximaciones* para representar funciones y operaciones complejas. Estas aproximaciones pueden producir dos tipos de errores:
- Errores de truncamiento: debido al uso expresiones aproximadas del procedimiento matemático exacto
- Errores de redondeo: debido a las limitaciones de representación numérica propias del computador

Para cuantificar el error utilizamos dos tipos de métricas

**Error absoluto** Corresponde al error neto de la propuesta numérica:

\begin{equation}
E_\mathrm{abs} = |\mathrm{valor~aproximado} - \mathrm{valor~exacto}|
\end{equation}

**Error relativo** Corresponde al error de la propuesta numérica respecto al valor exacto:

\begin{equation}
E_\mathrm{rel} = \frac{|\mathrm{valor~aproximado} - \mathrm{valor~exacto}|}{|\mathrm{valor~exacto}|}
\end{equation}

>**Nota** A veces, el error relativo se representa como porcentaje

Comúnmente, los métodos numéricos se basan en procesos iterativos donde una solución $x^k$ es mejorada en la iteración siguiente $x^{k+1}$. En el caso que la solución exacta no se conozca (caso más común), calculamos los errores como

- **Error absoluto** 

    \begin{equation}
    E_\mathrm{abs} = |x^{k+1} - x^{k}|
    \end{equation}

- **Error relativo** 

    \begin{equation}
    E_\mathrm{rel} = \frac{|x^{k+1} - x^{k}|}{|x^{k+1}|}
    \end{equation}

## Documentación de funciones en python

En python existen múltiples liberías, cada una con un propósito en específico. En este curso, trabajaremos con:
- `numpy`: Esencial para operaciones matemáticas con arreglos de elementos
- `pandas`: Útil para manejo de base de datos
- `matplotlib`: Herramientas para visualización de datos. En este curso utilizaremos particularmente el módulo `matplotlib.pyplot`.
- `scipy`: Funciones avanzadas para ciencia e ingeniería

A lo largo del curso iremos revisando las principales funciones de cada librería. En esta sección explicaremos como entender como acceder a la documentación oficial de cada función, y como interpretarla.

Para revisar la documentación de una función tenemos varias alternativas. Las más recomendadas son:
- Documentación oficial en línea
- Función `help`
- Caracter `?` al final de la función
- Comando `shift + tab`

>**Nota.** Por defecto, la documentación en línea está en base a la **última versión de la librería**. Es posible, sin embargo, encontrar la documentación para versiones anteriores.

Para verificar la versión de la librería que se está utilizando se debe usar el comando `library.__version__`, donde `library` corresponde a la librería en cuestión.

In [24]:
import numpy as np
print('versión de numpy: ' + np.__version__)

versión de numpy: 1.26.4


In [25]:
import matplotlib as mpl
print('versión de matplotlib: ' + mpl.__version__)

versión de matplotlib: 3.9.2


In [26]:
import scipy as sp
print('versión de scipy: ' + sp.__version__)

versión de scipy: 1.11.0


### Documentación en línea

Como ejercicio, consideremos la documentación de la función `linspace` de la libería `numpy`. Esta función será utilizada frecuentemente en el curso, y permite generar un arreglo de números distribuidos entre dos límites establecidos.

In [45]:
# generar un arreglo de 5 números entre 0 y 1
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Acá podemos ver un extracto de la documentación en línea (para la información completa ver [acá](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html))

<img src="./imagenes/linspace_online-doc.png" width="800" align= center>

Lo primero que vemos es el encabezado que muestra **todos los parámetros que necesita la función** (En este caso: `start`, `stop`, `num`, `endpoint`, `retstep`, `dtype` y `axis`). *La función esperará que todos los valores estén asignados, de lo contrario, arrojará un error.*

Luego, vemos parámetros con símbolo `=` (`num = 50`, por ejemplo). Esto indica que el parámetro **tiene un valor asignado por defecto**.

**Los parámetros con valor por defecto pueden ser omitidos al llamar a una función**. En ese caso python asumirá el valor asignado por defecto:

In [28]:
np.linspace(0,1)  # omitimos el parámetro "num"

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

El resultado es un arreglo de números igualmente espaciados entre 0 y 1, con `num = 50`.

Más abajo en la documentación, encontramos la descripción de cada parámetro. Notar que los valores con `=` están identificados como **opcional**.

<img src="./imagenes/linspace_online-doc_parameter.png" width="800" align= center>

Algunos parámetros no están disponibles en todas las versiones de la librería. Es el caso de `axis` de la función`linspace`, el cual está disponible desde la versión 1.16.0. en adelante.

<img src="./imagenes/linspace_online-doc_new-parameter.png" width="800" align= center>

Por último, tenemos el *output* de la función en el encabezado "**Return**"

<img src="./imagenes/linspace_online-doc_return.png" width="800" align= center>

Acá, por ejemplo, la documentación indica que la función entregará dos *outputs*, donde el primero corresponde al arreglo y el segundo, al espaciamiento entre valores. El segundo *output* es opcional, condicionado a la variable `retstep = True` (`False` por defecto).

In [29]:
vector, step = np.linspace(0,1,5,retstep=True)
print('Arreglo generado: ', vector)
print('Espaciamiento: ', step)

Arreglo generado:  [0.   0.25 0.5  0.75 1.  ]
Espaciamiento:  0.25


En python también podemos llamar a la función indicando el nombre de los parámetros de entrada

In [30]:
np.linspace(start=0, stop=1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Esta última forma es más conveniente para usuarios que no conocen la función, ya que permite identificar los parámetros de entrada

De igual forma, podemos cambiar el orden de los argumentos usando este esquema:

In [31]:
np.linspace(num=5, stop=1, start=0)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

###  Comandos directos para acceder a la documentación

La opción más directa es presionando `Shift + Tab` posicionando el cursor al final de la función. Este comando depende del *IDE* utilizado, pero funciona con *Jupyter Notebook*, *Visual Studio Code* y *Google colab*.

<img src="./imagenes/shift+tab.png" width="800" align= center>

Otra alternativa es con el comando `?` o con la función `help`
```python
np.linspace?
help(np.linspace)
```

## Referencias
Kong Q., Siauw T., Bayen A. M. “[Python Programming and Numerical Methods – A Guide for Engineers and Scientists](https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html)”, 1st Ed., Academic Press, 2021
- Chapter 8. Complexity
- Chapter 9. Representation of numbers
- Calítulo 10. Errors, Good Programming Practices, and Debugging